import Link from "next/link";
import { communityBuckets, resourceLinks } from "../data/community-content";
import { meetings } from "../data/site-content";

export function HomeContent() {
  return <>
    <section className="welcome-panel"><p className="eyebrow">Pine Valley, Utah</p><h1>A place to connect.<br />A community to care for.</h1><p className="intro">Find local activities, connect with community services, and stay informed about the decisions shaping Pine Valley.</p><div className="actions"><a className="button" href="#community">Explore community services</a><Link className="button button-outline" href="/public-documents/">Public documents</Link></div></section>
    <section id="community" aria-labelledby="community-heading"><div className="section-heading"><div><p className="eyebrow">Your community, at a glance</p><h2 id="community-heading">How can we help?</h2></div><p>Six places to find what you need.</p></div><div className="service-grid">{communityBuckets.map((bucket, index) => <Link className="service-card" key={bucket.slug} href={`/${bucket.slug}/`}><div className="service-meta"><span>{bucket.category}</span><span aria-hidden="true">0{index + 1}</span></div><h3>{bucket.title}</h3><p>{bucket.description}</p><span className="card-action">Explore <span aria-hidden="true">→</span></span></Link>)}</div></section>
    <section className="updates-panel" aria-labelledby="updates-heading"><div><p className="eyebrow">Stay informed</p><h2 id="updates-heading">Around Pine Valley</h2><p>Meeting information and seasonal community resources.</p><Link href="/community-events/">Community events →</Link></div><div className="update-list"><article><p className="eyebrow">Public meetings</p><h3>Special Service District</h3><p>{meetings.district}</p><p>{meetings.access}</p><Link href="/pvssd/#meetings">Meeting details & contacts →</Link></article><article><p className="eyebrow">History & heritage</p><h3>Pine Valley Heritage Center</h3><p>{meetings.heritage}</p><Link href="/pvhac/">Explore Pine Valley history →</Link></article></div></section>
    <section><p className="eyebrow">Useful links</p><h2>Community resources</h2><ul className="resource-grid">{resourceLinks.map((link) => <li key={link.href}><a href={link.href}>{link.label}<span aria-hidden="true">↗</span></a></li>)}</ul></section>
    <section className="help-panel"><div><p className="eyebrow">Get in touch</p><h2>Need a hand finding something?</h2><p>Send questions or website suggestions to <a href="mailto:pine.valley.webmaster@gmail.com">pine.valley.webmaster@gmail.com</a>.</p></div><div><h3>Report Fraud, Waste, or Abuse</h3><p>Submit a report through the Washington County Auditor.</p><a href="https://www.washco.utah.gov/departments/auditor/report-fraud-waste-abuse/">Washington County reporting form →</a></div></section>
  </>;
}
